<figure>
    <center>
    <img src="../../figures/kinki2.png"  width="400" height="370" align="center"/>
    </center>
</figure>

# <span style="color:blue"><center>Hackathon: Shinkansen Travel Experience</center></span>

# <span style="color:red"><center>Process studied</center></span>

## <span style="color:green"><center> Ensembling learning </center></span>

## <span style="color:blue">Authors</span>

1. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com
1. Juan Felipe Contreras Alcívar, j.contrerasa94@gmail.com

## <span style="color:blue">Libraries</span>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, VotingClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


import catboost
import xgboost

import warnings
warnings.filterwarnings('ignore')

## <span style="color:blue"> Importing Data </span>

In [2]:
train_df = pd.read_csv('../../input/train/imputed_no_response_df.csv', sep=';', index_col=0)
test_df = pd.read_csv('../../input/test/imputed_no_response_df.csv', sep=';', index_col=0)

train_df

Overall_Experience   Age  Travel_Distance  Departure_Delay_in_Mins  \
ID                                                                             
98800001                   0  52.0              272                      0.0   
98800002                   0  48.0             2200                      9.0   
98800003                   1  43.0             1061                     77.0   
98800004                   0  44.0              780                     13.0   
98800005                   1  50.0             1981                      0.0   
...                      ...   ...              ...                      ...   
98894375                   0  32.0             1357                     83.0   
98894376                   1  44.0              592                      5.0   
98894377                   1  63.0             2794                      0.0   
98894378                   0  16.0             2744                      0.0   
98894379                   0  54.0             2107                     28.0   

          Arrival_Delay_in_Mins  Gender   Customer_Type      Type_Travel  \
ID                                                                         
98800001                    5.0  Female  Loyal Customer      No_response   
98800002                    0.0    Male  Loyal Customer  Personal Travel   
98800003                  119.0  Female  Loyal Customer  Business Travel   
98800004                   18.0  Female  Loyal Customer  Business Travel   
98800005                    0.0  Female  Loyal Customer  Business Travel   
...                         ...     ...             ...              ...   
98894375                  125.0    Male  Loyal Customer  Business Travel   
98894376                   11.0    Male  Loyal Customer  Business Travel   
98894377                    0.0    Male     No_response  Business Travel   
98894378                    0.0    Male  Loyal Customer  Personal Travel   
98894379                   28.0    Male  Loyal Customer      No_response   

         Travel_Class       Seat_Comfort  ... Onboard_Wifi_Service  \
ID                                        ...                        
98800001     Business  Needs Improvement  ...                 Good   
98800002          Eco               Poor  ...                 Good   
98800003     Business  Needs Improvement  ...    Needs Improvement   
98800004     Business         Acceptable  ...           Acceptable   
98800005     Business         Acceptable  ...    Needs Improvement   
...               ...                ...  ...                  ...   
98894375     Business               Poor  ...                 Poor   
98894376     Business               Good  ...    Needs Improvement   
98894377     Business  Needs Improvement  ...                 Good   
98894378          Eco  Needs Improvement  ...                 Good   
98894379          Eco         Acceptable  ...           Acceptable   

         Onboard_Entertainment Online_Support Ease_of_Online_Booking  \
ID                                                                     
98800001     Needs Improvement     Acceptable      Needs Improvement   
98800002                  Poor           Good                   Good   
98800003                  Good      Excellent              Excellent   
98800004     Needs Improvement     Acceptable             Acceptable   
98800005                  Good      Excellent                   Good   
...                        ...            ...                    ...   
98894375                  Poor           Poor                   Poor   
98894376             Excellent      Excellent             Acceptable   
98894377             Excellent           Good                   Good   
98894378     Needs Improvement           Good                   Good   
98894379            Acceptable     Acceptable             Acceptable   

            Onboard_Service            Legroom   Baggage_Handling  \
ID                                                             

## <span style="color:blue"> Feature engineer </span>

In [3]:
train_df['train_test'] = 'train'
test_df['train_test'] = 'test'

df = pd.concat([train_df, test_df])

In [4]:
df

Overall_Experience   Age  Travel_Distance  Departure_Delay_in_Mins  \
ID                                                                             
98800001                 0.0  52.0              272                      0.0   
98800002                 0.0  48.0             2200                      9.0   
98800003                 1.0  43.0             1061                     77.0   
98800004                 0.0  44.0              780                     13.0   
98800005                 1.0  50.0             1981                      0.0   
...                      ...   ...              ...                      ...   
99935598                 NaN   8.0             1334                      0.0   
99935599                 NaN  53.0             1772                      0.0   
99935600                 NaN  22.0             1180                      0.0   
99935601                 NaN  67.0              420                     23.0   
99935602                 NaN  20.0             1680                      0.0   

          Arrival_Delay_in_Mins  Gender      Customer_Type      Type_Travel  \
ID                                                                            
98800001                    5.0  Female     Loyal Customer      No_response   
98800002                    0.0    Male     Loyal Customer  Personal Travel   
98800003                  119.0  Female     Loyal Customer  Business Travel   
98800004                   18.0  Female     Loyal Customer  Business Travel   
98800005                    0.0  Female     Loyal Customer  Business Travel   
...                         ...     ...                ...              ...   
99935598                    0.0    Male     Loyal Customer  Personal Travel   
99935599                    0.0  Female     Loyal Customer  Business Travel   
99935600                    0.0    Male  Disloyal Customer  Business Travel   
99935601                   16.0  Female     Loyal Customer  Personal Travel   
99935602                    0.0    Male        No_response  Personal Travel   

         Travel_Class       Seat_Comfort  ... Onboard_Entertainment  \
ID                                        ...                         
98800001     Business  Needs Improvement  ...     Needs Improvement   
98800002          Eco               Poor  ...                  Poor   
98800003     Business  Needs Improvement  ...                  Good   
98800004     Business         Acceptable  ...     Needs Improvement   
98800005     Business         Acceptable  ...                  Good   
...               ...                ...  ...                   ...   
99935598          Eco  Needs Improvement  ...     Needs Improvement   
99935599     Business  Needs Improvement  ...             Excellent   
99935600          Eco               Good  ...                  Good   
99935601          Eco          Excellent  ...             Excellent   
99935602          Eco               Good  ...                  Good   

         Online_Support Ease_of_Online_Booking    Onboard_Service  \
ID                                                                  
98800001     Acceptable      Needs Improvement  Needs Improvement   
98800002           Good                   Good          Excellent   
98800003      Excellent              Excellent          Excellent   
98800004     Acceptable             Acceptable         Acceptable   
98800005      Excellent                   Good               Good   
...                 ...                    ...                ...   
99935598     Acceptable             Acceptable               Good   
99935599      Excellent                   Good               Good   
99935600           Poor      Needs Improvement               Poor   
99935601           Good              Excellent          Excellent   
99935602           Poor                   Poor         Acceptable   

                    Legroom   Baggage_Handling    CheckIn_Service  \
ID                                                

In [5]:
numerical_columns = ['Age', 'Travel_Distance', 'Departure_Delay_in_Mins', 'Arrival_Delay_in_Mins']

In [6]:
df = pd.get_dummies(df, columns = [x for x in df.columns if x not in ['train_test', 'Overall_Experience'] + numerical_columns])
df

Overall_Experience   Age  Travel_Distance  Departure_Delay_in_Mins  \
ID                                                                             
98800001                 0.0  52.0              272                      0.0   
98800002                 0.0  48.0             2200                      9.0   
98800003                 1.0  43.0             1061                     77.0   
98800004                 0.0  44.0              780                     13.0   
98800005                 1.0  50.0             1981                      0.0   
...                      ...   ...              ...                      ...   
99935598                 NaN   8.0             1334                      0.0   
99935599                 NaN  53.0             1772                      0.0   
99935600                 NaN  22.0             1180                      0.0   
99935601                 NaN  67.0              420                     23.0   
99935602                 NaN  20.0             1680                      0.0   

          Arrival_Delay_in_Mins train_test  Gender_Female  Gender_Male  \
ID                                                                       
98800001                    5.0      train           True        False   
98800002                    0.0      train          False         True   
98800003                  119.0      train           True        False   
98800004                   18.0      train           True        False   
98800005                    0.0      train           True        False   
...                         ...        ...            ...          ...   
99935598                    0.0       test          False         True   
99935599                    0.0       test           True        False   
99935600                    0.0       test          False         True   
99935601                   16.0       test           True        False   
99935602                    0.0       test          False         True   

          Gender_No_response  Customer_Type_Disloyal Customer  ...  \
ID                                                             ...   
98800001               False                            False  ...   
98800002               False                            False  ...   
98800003               False                            False  ...   
98800004               False                            False  ...   
98800005               False                            False  ...   
...                      ...                              ...  ...   
99935598               False                            False  ...   
99935599               False                            False  ...   
99935600               False                             True  ...   
99935601               False                            False  ...   
99935602               False                            False  ...   

          Cleanliness_Needs Improvement  Cleanliness_No_response  \
ID                                                                 
98800001                           True                    False   
98800002                          False                    False   
98800003                          False                    False   
98800004                          False                    False   
98800005                          False                    False   
...                                 ...                      ...   
99935598                          False                    False   
99935599                          False                    False   
99935600                          False                    False   
99935601                          False                    False   
99935602                          False                    False   

          Cleanliness_Poor  Online_Boarding_Acceptable  \
ID                                                       
98800001             False                       False   
98800002             False          

In [7]:
scaler = StandardScaler()

In [8]:
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])
df

Overall_Experience       Age  Travel_Distance  \
ID                                                        
98800001                 0.0  0.831555        -1.664281   
98800002                 0.0  0.567000         0.213103   
98800003                 1.0  0.236305        -0.895995   
98800004                 0.0  0.302444        -1.169618   
98800005                 1.0  0.699278        -0.000148   
...                      ...       ...              ...   
99935598                 NaN -2.078556        -0.630162   
99935599                 NaN  0.897694        -0.203661   
99935600                 NaN -1.152612        -0.780119   
99935601                 NaN  1.823639        -1.520167   
99935602                 NaN -1.284889        -0.293245   

          Departure_Delay_in_Mins  Arrival_Delay_in_Mins train_test  \
ID                                                                    
98800001                -0.386526              -0.262755      train   
98800002                -0.150055              -0.392986      train   
98800003                 1.636619               2.706501      train   
98800004                -0.044957               0.075844      train   
98800005                -0.386526              -0.392986      train   
...                           ...                    ...        ...   
99935598                -0.386526              -0.392986       test   
99935599                -0.386526              -0.392986       test   
99935600                -0.386526              -0.392986       test   
99935601                 0.217790               0.023752       test   
99935602                -0.386526              -0.392986       test   

          Gender_Female  Gender_Male  Gender_No_response  \
ID                                                         
98800001           True        False               False   
98800002          False         True               False   
98800003           True        False               False   
98800004           True        False               False   
98800005           True        False               False   
...                 ...          ...                 ...   
99935598          False         True               False   
99935599           True        False               False   
99935600          False         True               False   
99935601           True        False               False   
99935602          False         True               False   

          Customer_Type_Disloyal Customer  ...  Cleanliness_Needs Improvement  \
ID                                         ...                                  
98800001                            False  ...                           True   
98800002                            False  ...                          False   
98800003                            False  ...                          False   
98800004                            False  ...                          False   
98800005                            False  ...                          False   
...                                   ...  ...                            ...   
99935598                            False  ...                          False   
99935599                            False  ...                          False   
99935600                             True  ...                          False   
99935601                            False  ...                          False   
99935602                            False  ...                          False   

          Cleanliness_No_response  Cleanliness_Poor  \
ID                                                    
98800001                    False             False   
98800002                    False             False   
98800003                    False             False   
98800004                    False             False   
98800005                    False             False   
...                           ...               ...   
99935598                    False          

## <span style="color:blue"> Train/test split </span>

In [9]:
train_df = df[df['train_test']=='train']
test_df = df[df['train_test']=='test']

In [10]:
# Define features and target variable
X_train = train_df.drop(columns=['Overall_Experience', 'train_test'])
y_train = train_df['Overall_Experience']

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, stratify=y_train, random_state=42, shuffle=True, test_size=0.2)

X_test = test_df.drop(['train_test', 'Overall_Experience'], axis=1)

In [11]:
y_train.value_counts()

Overall_Experience
1.0    41274
0.0    34229
Name: count, dtype: int64

In [12]:
X_train.shape

(75503, 114)

In [13]:
X_val.shape

(18876, 114)

## <span style="color:blue"> Models </span>

### <span style="color:#4CC9F0"> Catboost </span>

In [14]:
cb = catboost.CatBoostClassifier(depth = 8, 
                                 verbose=0, 
                                 iterations = 1000, 
                                 l2_leaf_reg = 7, 
                                 learning_rate = 0.1,
                                 scale_pos_weight=(sum(y_train == 0) / sum(y_train == 1)))

In [15]:
cb.fit(X_train, y_train)

In [16]:
prob_cut = 0.5

In [17]:
# Evaluate the model
y_pred_prob = cb.predict_proba(X_train)
prob_train = y_pred_prob[:, 1]
y_pred_train =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Ensemble - Accuracy: 0.9935366806616955, F1 Score: 0.9935388752492083
Classification Report:
               precision    recall  f1-score   support

         0.0       0.99      1.00      0.99     34229
         1.0       1.00      0.99      0.99     41274

    accuracy                           0.99     75503
   macro avg       0.99      0.99      0.99     75503
weighted avg       0.99      0.99      0.99     75503

Confusion Matrix:
 [[34127   102]
 [  386 40888]]


In [18]:
prob_cut = 0.5

In [19]:
# Evaluate the model
y_pred_prob = cb.predict_proba(X_val)
prob_val = y_pred_prob[:, 1]
y_pred_val =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

Ensemble - Accuracy: 0.9571943208306845, F1 Score: 0.9572337428058051
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.97      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.96      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8258  299]
 [ 509 9810]]


### <span style="color:#4CC9F0"> XGBoost </span>

In [20]:
xgb = xgboost.XGBClassifier(n_estimators=300, max_depth=10,
                            max_leaves=64,
                            eta=0.1,
                            reg_lambda=0,
                            tree_method='hist',
                            eval_metric='logloss',
                            use_label_encoder=False,
                            random_state=42)

In [21]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
              max_leaves=64, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [22]:
prob_cut = 0.5

In [23]:
# Evaluate the model
y_pred_prob = xgb.predict_proba(X_train)
prob_train = y_pred_prob[:, 1]
y_pred_train =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Ensemble - Accuracy: 0.9818020476007576, F1 Score: 0.9818093827732003
Classification Report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98     34229
         1.0       0.99      0.98      0.98     41274

    accuracy                           0.98     75503
   macro avg       0.98      0.98      0.98     75503
weighted avg       0.98      0.98      0.98     75503

Confusion Matrix:
 [[33712   517]
 [  857 40417]]


In [24]:
prob_cut = 0.5

In [25]:
# Evaluate the model
y_pred_prob = xgb.predict_proba(X_val)
prob_val = y_pred_prob[:, 1]
y_pred_val =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

Ensemble - Accuracy: 0.9553930917567282, F1 Score: 0.9554261383410158
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.95      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8218  339]
 [ 503 9816]]


### <span style="color:#4CC9F0"> Voting classifier </span>

In [26]:
estimators = [('gb', GradientBoostingClassifier(learning_rate = 0.1, 
                                                max_depth=5, 
                                                n_estimators=1000,
                                                random_state=42, 
                                                subsample=0.7)), 
              
              ('rf', RandomForestClassifier(min_samples_leaf = 10, 
                                            min_samples_split = 10, 
                                            n_jobs=-1,
                                            n_estimators = 1000)),
              
              ('cb', catboost.CatBoostClassifier(depth = 8, 
                                                 verbose=0, 
                                                 iterations = 1000, 
                                                 l2_leaf_reg = 7, 
                                                 learning_rate = 0.1,
                                                 scale_pos_weight=(sum(y_train == 0) / sum(y_train == 1)))), 
              
              ('xgb', xgboost.XGBClassifier(n_estimators=300,
                                            max_depth=10,
                                            max_leaves=64,
                                            eta=0.1,
                                            reg_lambda=0,
                                            tree_method='hist',
                                            eval_metric='logloss',
                                            use_label_encoder=False,
                                            random_state=42, 
                                            scale_pos_weight=(sum(y_train == 0) / sum(y_train == 1))))
             ]
              
#              ('ab', AdaBoostClassifier(learning_rate=1, n_estimators=200, random_state=42))]

In [27]:
voting_clf = VotingClassifier(
    estimators = estimators,
    voting='soft'
)

In [28]:
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('gb',
                              GradientBoostingClassifier(max_depth=5,
                                                         n_estimators=1000,
                                                         random_state=42,
                                                         subsample=0.7)),
                             ('rf',
                              RandomForestClassifier(min_samples_leaf=10,
                                                     min_samples_split=10,
                                                     n_estimators=1000,
                                                     n_jobs=-1)),
                             ('cb',
                              <catboost.core.CatBoostClassifier object at 0x308827310>),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,...
                                            feature_types=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=10,
                                            max_leaves=64,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=300, n_jobs=None,
                                            num_parallel_tree=None, ...))],
                 voting='soft')

In [29]:
prob_cut = 0.5

In [30]:
# Evaluate the model
y_pred_prob = voting_clf.predict_proba(X_train)
prob_train = y_pred_prob[:, 1]
y_pred_train =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Ensemble - Accuracy: 0.9879739877885647, F1 Score: 0.9879797712098594
Classification Report:
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99     34229
         1.0       0.99      0.98      0.99     41274

    accuracy                           0.99     75503
   macro avg       0.99      0.99      0.99     75503
weighted avg       0.99      0.99      0.99     75503

Confusion Matrix:
 [[33980   249]
 [  659 40615]]


In [31]:
# Evaluate the model
y_pred_prob = voting_clf.predict_proba(X_val)
prob_val = y_pred_prob[:, 1]
y_pred_val = np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

Ensemble - Accuracy: 0.9573002754820936, F1 Score: 0.9573402442316882
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.97      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.96      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8261  296]
 [ 510 9809]]


In [32]:
prob_cut = 0.5

In [33]:
# Evaluate the model
y_pred_prob = voting_clf.predict_proba(X_train)
prob_train = y_pred_prob[:, 1]
y_pred_train =  np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Ensemble - Accuracy: 0.9879739877885647, F1 Score: 0.9879797712098594
Classification Report:
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99     34229
         1.0       0.99      0.98      0.99     41274

    accuracy                           0.99     75503
   macro avg       0.99      0.99      0.99     75503
weighted avg       0.99      0.99      0.99     75503

Confusion Matrix:
 [[33980   249]
 [  659 40615]]


In [34]:
# Evaluate the model
y_pred_prob = voting_clf.predict_proba(X_val)
prob_val = y_pred_prob[:, 1]
y_pred_val = np.int64(y_pred_prob[:, 1] > prob_cut)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

Ensemble - Accuracy: 0.9573002754820936, F1 Score: 0.9573402442316882
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.97      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.96      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8261  296]
 [ 510 9809]]


In [35]:
prob_cut= 0.5

In [36]:
for clf in voting_clf.estimators_:
    
    y_pred_prob = clf.predict_proba(X_val)    
    prob_val = y_pred_prob[:, 1]
    y_pred_val = np.int64(y_pred_prob[:, 1] > prob_cut)

    print(accuracy_score(y_val, y_pred_val))

0.954227590591227
0.9392879847425302
0.9571943208306845
0.9558169103623649


In [37]:
base_gb = GradientBoostingClassifier(learning_rate = 0.2, 
                                     max_depth=10, 
                                     n_estimators=500,
                                     random_state=42)

pasting_clf = BaggingClassifier(estimator=base_gb, n_estimators=10, n_jobs=-1, verbose=3)

In [38]:
pasting_clf.fit(X_train, y_train)

[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   3 out of  10 | elapsed:  4.2min remaining:  9.8min
[Parallel(n_jobs=10)]: Done   7 out of  10 | elapsed:  4.2min remaining:  1.8min
[Parallel(n_jobs=10)]: Done  10 out of  10 | elapsed:  4.2min finished


BaggingClassifier(estimator=GradientBoostingClassifier(learning_rate=0.2,
                                                       max_depth=10,
                                                       n_estimators=500,
                                                       random_state=42),
                  n_jobs=-1, verbose=3)

In [39]:
# Evaluate the model
y_pred_prob = pasting_clf.predict(X_train)
y_pred_train =  np.round(y_pred_prob)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   3 out of  10 | elapsed:    2.2s remaining:    5.1s
[Parallel(n_jobs=10)]: Done   7 out of  10 | elapsed:    2.8s remaining:    1.2s
[Parallel(n_jobs=10)]: Done  10 out of  10 | elapsed:    3.4s finished


Ensemble - Accuracy: 0.9964902056871913, F1 Score: 0.9964906156619784
Classification Report:
               precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     34229
         1.0       1.00      1.00      1.00     41274

    accuracy                           1.00     75503
   macro avg       1.00      1.00      1.00     75503
weighted avg       1.00      1.00      1.00     75503

Confusion Matrix:
 [[34144    85]
 [  180 41094]]


In [40]:
# Evaluate the model
y_pred_prob = pasting_clf.predict(X_val)
y_pred_val =  np.round(y_pred_prob)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done   3 out of  10 | elapsed:    0.7s remaining:    1.6s
[Parallel(n_jobs=10)]: Done   7 out of  10 | elapsed:    1.1s remaining:    0.5s


Ensemble - Accuracy: 0.9582008900190718, F1 Score: 0.9582340353684579
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.96      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8251  306]
 [ 483 9836]]


[Parallel(n_jobs=10)]: Done  10 out of  10 | elapsed:    1.5s finished


In [41]:
xgb = xgboost.XGBClassifier(n_estimators=300,
                                max_depth=10,
                                max_leaves=64,
                                eta=0.1,
                                reg_lambda=0,
                                tree_method='hist',
                                eval_metric='logloss',
                                use_label_encoder=False,
                                random_state=42)

In [42]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
              max_leaves=64, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [43]:
# Evaluate the model
y_pred_prob = xgb.predict(X_train)
y_pred_train =  np.round(y_pred_prob)

accuracy_nn = accuracy_score(y_train, y_pred_train)
f1_nn = f1_score(y_train, y_pred_train, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Ensemble - Accuracy: 0.9818020476007576, F1 Score: 0.9818093827732003
Classification Report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98     34229
         1.0       0.99      0.98      0.98     41274

    accuracy                           0.98     75503
   macro avg       0.98      0.98      0.98     75503
weighted avg       0.98      0.98      0.98     75503

Confusion Matrix:
 [[33712   517]
 [  857 40417]]


In [44]:
# Evaluate the model
y_pred_prob = xgb.predict(X_val)
y_pred_val =  np.round(y_pred_prob)

accuracy_nn = accuracy_score(y_val, y_pred_val)
f1_nn = f1_score(y_val, y_pred_val, average='weighted')
print(f"Ensemble - Accuracy: {accuracy_nn}, F1 Score: {f1_nn}")
print("Classification Report:\n", classification_report(y_val, y_pred_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

Ensemble - Accuracy: 0.9553930917567282, F1 Score: 0.9554261383410158
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      8557
         1.0       0.97      0.95      0.96     10319

    accuracy                           0.96     18876
   macro avg       0.95      0.96      0.96     18876
weighted avg       0.96      0.96      0.96     18876

Confusion Matrix:
 [[8218  339]
 [ 503 9816]]


In [45]:
voting_clf.estimators_

[GradientBoostingClassifier(max_depth=5, n_estimators=1000, random_state=42,
                            subsample=0.7),
 RandomForestClassifier(min_samples_leaf=10, min_samples_split=10,
                        n_estimators=1000, n_jobs=-1),
 XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eta=0.1, eval_metric='logloss',
               feature_types=None, gamma=None, grow_policy=None,
               importance_type=None, interaction_constraints=None,
               learning_rate=None, max_bin=None, max_cat_threshold=None,
               max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
               max_leaves=64, min_child_weight=None, missing=nan,
               monotone_constraints=None, multi_strategy=None, n_estimators=300,
               n_jobs=None, num_parallel_tree=None, ...